# This file was generated by the docusign_rest:generate_config rake task.
# You can run 'rake docusign_rest:generate_config' as many times as you need
# to replace the content of this file with a new config.

require 'docusign_rest'

DocusignRest.configure do |config|
  config.username       = 'mark@wilsonsdev.com'
  config.password       = '9*@s-RtFqDt-pBc47OvGzAZte'
  config.integrator_key = '25e1e0bd-0713-47dc-9a2f-28c09c246b00'
  config.account_id     = '2127355'
  #config.endpoint       = 'https://www.docusign.net/restapi'
  #config.api_version    = 'v1'
end

